sudo: false
language: node_js
node_js:
  - stable
  - 6
  - 5
cache:
  directories:
  - node_modules
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
script:
  - npm test
